version: "3"
services:
  db:
    image: mongo
    ports:
    - "27017:27017"
  web:
    build: .
    volumes:
      - ./:/app
    ports:
    - "3000:3000"
    links:
    - db
    command: nodemon /app/bin/www



